/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Campaign
 */
export interface Campaign {
  /**
   * id
   * @type {string}
   * @memberof Campaign
   */
  id: string;
  /**
   * キャンペーンの名前
   * @type {string}
   * @memberof Campaign
   */
  name: string;
  /**
   * キャンペーンのサムネイル画像のURL
   * @type {string}
   * @memberof Campaign
   */
  thumbnail: string;
}

export function CampaignFromJSON(json: any): Campaign {
  return CampaignFromJSONTyped(json, false);
}

export function CampaignFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Campaign {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    thumbnail: json['thumbnail'],
  };
}

export function CampaignToJSON(value?: Campaign | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    thumbnail: value.thumbnail,
  };
}
