/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * カテゴリのmodel
 * @export
 * @interface Category
 */
export interface Category {
  /**
   * id
   * @type {string}
   * @memberof Category
   */
  id: string;
  /**
   * カテゴリの名前
   * @type {string}
   * @memberof Category
   */
  name: string;
  /**
   * カテゴリのサムネイル画像のURL
   * @type {string}
   * @memberof Category
   */
  thumbnail: string;
}

export function CategoryFromJSON(json: any): Category {
  return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Category {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    thumbnail: json['thumbnail'],
  };
}

export function CategoryToJSON(value?: Category | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    thumbnail: value.thumbnail,
  };
}
