/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DetailContent
 */
export interface DetailContent {
  /**
   * ヘッダー
   * @type {string}
   * @memberof DetailContent
   */
  header: string;
  /**
   * 内容
   * @type {string}
   * @memberof DetailContent
   */
  content: string;
}

export function DetailContentFromJSON(json: any): DetailContent {
  return DetailContentFromJSONTyped(json, false);
}

export function DetailContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DetailContent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    header: json['header'],
    content: json['content'],
  };
}

export function DetailContentToJSON(value?: DetailContent | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    header: value.header,
    content: value.content,
  };
}
