/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag, TagFromJSON, TagToJSON } from './Tag';

/**
 * お知らせのmodel
 * @export
 * @interface Information
 */
export interface Information {
  /**
   *
   * @type {string}
   * @memberof Information
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Information
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Information
   */
  detail: string;
  /**
   *
   * @type {Array<Tag>}
   * @memberof Information
   */
  tags: Array<Tag>;
  /**
   *
   * @type {string}
   * @memberof Information
   */
  announced_at: string;
}

export function InformationFromJSON(json: any): Information {
  return InformationFromJSONTyped(json, false);
}

export function InformationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Information {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    detail: json['detail'],
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    announced_at: json['announced_at'],
  };
}

export function InformationToJSON(value?: Information | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    detail: value.detail,
    tags: (value.tags as Array<any>).map(TagToJSON),
    announced_at: value.announced_at,
  };
}
