/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Promotion
 */
export interface Promotion {
  /**
   * id
   * @type {string}
   * @memberof Promotion
   */
  id: string;
  /**
   * プロモーションのタイトル
   * @type {string}
   * @memberof Promotion
   */
  title: string;
  /**
   * プロモーションの画像のURL
   * @type {string}
   * @memberof Promotion
   */
  image: string;
  /**
   * プロモーションの詳細
   * @type {string}
   * @memberof Promotion
   */
  detail: string;
  /**
   * プロモーションのリンクのURL
   * @type {string}
   * @memberof Promotion
   */
  link: string;
}

export function PromotionFromJSON(json: any): Promotion {
  return PromotionFromJSONTyped(json, false);
}

export function PromotionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Promotion {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    image: json['image'],
    detail: json['detail'],
    link: json['link'],
  };
}

export function PromotionToJSON(value?: Promotion | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    image: value.image,
    detail: value.detail,
    link: value.link,
  };
}
