/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShopItem, ShopItemFromJSON, ShopItemToJSON } from './ShopItem';
import { Tag, TagFromJSON, TagToJSON } from './Tag';
import { Price, PriceFromJSON, PriceToJSON } from './Price';
import {
  DetailContent,
  DetailContentFromJSON,
  DetailContentToJSON,
} from './DetailContent';
import { Category, CategoryFromJSON, CategoryToJSON } from './Category';
import { Campaign, CampaignFromJSON, CampaignToJSON } from './Campaign';

/**
 * 商品の詳細情報のmodel
 * @export
 * @interface ShopItemDetail
 */
export interface ShopItemDetail {
  /**
   * id
   * @type {string}
   * @memberof ShopItemDetail
   */
  id: string;
  /**
   * 商品の名前
   * @type {string}
   * @memberof ShopItemDetail
   */
  name: string;
  /**
   * サムネイル画像のURL
   * @type {string}
   * @memberof ShopItemDetail
   */
  thumbnail: string;
  /**
   *
   * @type {Price}
   * @memberof ShopItemDetail
   */
  price: Price;
  /**
   * タグの配列
   * @type {Array<Tag>}
   * @memberof ShopItemDetail
   */
  tags: Array<Tag>;
  /**
   * カテゴリのの配列
   * @type {Array<Category>}
   * @memberof ShopItemDetail
   */
  categories: Array<Category>;
  /**
   * キャンペーンの配列
   * @type {Array<Campaign>}
   * @memberof ShopItemDetail
   */
  campaigns: Array<Campaign>;
  /**
   * 商品の詳細
   * @type {Array<DetailContent>}
   * @memberof ShopItemDetail
   */
  details: Array<DetailContent>;
  /**
   * 画像のURLの配列
   * @type {Array<string>}
   * @memberof ShopItemDetail
   */
  images: Array<string>;
  /**
   * 関連商品の配列
   * @type {Array<ShopItem>}
   * @memberof ShopItemDetail
   */
  related_shop_items: Array<ShopItem>;
}

export function ShopItemDetailFromJSON(json: any): ShopItemDetail {
  return ShopItemDetailFromJSONTyped(json, false);
}

export function ShopItemDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ShopItemDetail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    thumbnail: json['thumbnail'],
    price: PriceFromJSON(json['price']),
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    categories: (json['categories'] as Array<any>).map(CategoryFromJSON),
    campaigns: (json['campaigns'] as Array<any>).map(CampaignFromJSON),
    details: (json['details'] as Array<any>).map(DetailContentFromJSON),
    images: json['images'],
    related_shop_items: (json['related_shop_items'] as Array<any>).map(
      ShopItemFromJSON,
    ),
  };
}

export function ShopItemDetailToJSON(value?: ShopItemDetail | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    thumbnail: value.thumbnail,
    price: PriceToJSON(value.price),
    tags: (value.tags as Array<any>).map(TagToJSON),
    categories: (value.categories as Array<any>).map(CategoryToJSON),
    campaigns: (value.campaigns as Array<any>).map(CampaignToJSON),
    details: (value.details as Array<any>).map(DetailContentToJSON),
    images: value.images,
    related_shop_items: (value.related_shop_items as Array<any>).map(
      ShopItemToJSON,
    ),
  };
}
