/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TagGroup, TagGroupFromJSON, TagGroupToJSON } from './TagGroup';

/**
 *
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   * id
   * @type {string}
   * @memberof Tag
   */
  id: string;
  /**
   * タグの名称
   * @type {string}
   * @memberof Tag
   */
  name: string;
  /**
   * html5でcolorとして扱える文字列
   * @type {string}
   * @memberof Tag
   */
  color: string;
  /**
   *
   * @type {TagGroup}
   * @memberof Tag
   */
  tag_group: TagGroup;
}

export function TagFromJSON(json: any): Tag {
  return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    color: json['color'],
    tag_group: TagGroupFromJSON(json['tag_group']),
  };
}

export function TagToJSON(value?: Tag | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    color: value.color,
    tag_group: TagGroupToJSON(value.tag_group),
  };
}
