/* tslint:disable */
/* eslint-disable */
/**
 * yumeshop
 * yumeshopのAPIが定義されています。
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * タグのグループを表すenum
 * shop_item: 商品のタググループ
 * information: お知らせのタググループ
 * @export
 * @enum {string}
 */
export enum TagGroup {
  ShopItem = 'shop_item',
  Information = 'information',
}

export function TagGroupFromJSON(json: any): TagGroup {
  return TagGroupFromJSONTyped(json, false);
}

export function TagGroupFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagGroup {
  return json as TagGroup;
}

export function TagGroupToJSON(value?: TagGroup | null): any {
  return value as any;
}
